name: Node.js Package Version
description: Retrieve the package version for a Node.js project
author: Malomo
branding:
  color: red
  icon: package
inputs:
  filePath:
    default: ./package.json
    description: Path to the package.json containing the version to retrieve
    required: false
  prefix:
    description: Prepend to version
    required: false
  suffix:
    description: Append to version
    required: false
outputs:
  version:
    description: Version retrieved for the Node.js project
runs:
  main: index.js
  using: node12
